version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST="127.0.0.1"
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="123"
      - POSTGRES_DB="api_database"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "api_database"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: